[package]
name = "mado-rune-macros"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ['full', 'extra-traits'] }
quote = "1.0"


[dev-dependencies]
rune = "0.10"
rune-modules = "0.12"
