[package]
name = "mado-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
thiserror = "1.0"
anyhow = "1"
async-trait = "0.1"
tracing = "0.1"

[dependencies.tokio]
version = "1"
features = [
  "sync"
]

[dependencies.mado-core]
path = "../core"
