[package]
name = "mado-relm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.3", package = "gtk4" }
gio = { version = "0.14" }
relm4 = "0.2"
relm4-macros = "0.2"
relm4-components = "0.2"

tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

thiserror = "1.0"

mado-core = { path = "../core" }

mado-rune = { path = "../rune" }
