name: Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Cache Target
      id: cache-target
      uses: actions/cache@v3
      with:
        path: |
          target
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cache

    - name: Dependency
      run: sudo apt-get install libgtk-4-dev

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Generate code coverage
      run: |
        cargo install cargo-tarpaulin
        cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml


    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
          fail_ci_if_error:     true
